export const DEGREES: readonly string[] = [
	'Associate of Arts',
	'Associate of Science',
	'Associate of Applied Arts',
	'Associate of Applied Science',
	'Associate of Business Administration',
	'Associate of Engineering',
	'Associate of Fine Arts',
	'Associate Degree',
	'Bachelor of Architecture',
	'Bachelor of Arts',
	'Bachelor of Applied Science',
	'Bachelor of Biomedical Science',
	'Bachelor of Business Administration',
	'Bachelor of Commerce',
	'Bachelor of Computer Applications',
	'Bachelor of Computer Science',
	'Bachelor of Dental Surgery',
	'Bachelor of Design',
	'Bachelor of Economics',
	'Bachelor of Education',
	'Bachelor of Engineering',
	'Bachelor of Finance',
	'Bachelor of Fine Arts',
	'Bachelor of Information Systems',
	'Bachelor of Information Technology',
	'Bachelor of Journalism',
	'Bachelor of Laws',
	'Bachelor of Liberal Arts',
	'Bachelor of Music',
	'Bachelor of Nursing',
	'Bachelor of Pharmacy',
	'Bachelor of Public Administration',
	'Bachelor of Science',
	'Bachelor of Science in Nursing',
	'Bachelor of Social Work',
	'Bachelor of Technology',
	'Master of Accounting',
	'Master of Architecture',
	'Master of Arts',
	'Master of Applied Science',
	'Master of Business Administration',
	'Master of Commerce',
	'Master of Computer Applications',
	'Master of Computer Science',
	'Master of Data Science',
	'Master of Divinity',
	'Master of Education',
	'Master of Engineering',
	'Master of Finance',
	'Master of Fine Arts',
	'Master of Health Administration',
	'Master of Information Systems',
	'Master of Information Technology',
	'Master of Journalism',
	'Master of Laws',
	'Master of Letters',
	'Master of Music',
	'Master of Public Administration',
	'Master of Public Health',
	'Master of Public Policy',
	'Master of Science',
	'Master of Social Work',
	'Doctor of Business Administration',
	'Doctor of Dental Medicine',
	'Doctor of Dental Surgery',
	'Doctor of Education',
	'Doctor of Engineering',
	'Doctor of Juridical Science',
	'Doctor of Medicine',
	'Doctor of Ministry',
	'Doctor of Nursing Practice',
	'Doctor of Optometry',
	'Doctor of Pharmacy',
	'Doctor of Philosophy',
	'Doctor of Physical Therapy',
	'Doctor of Psychology',
	'Doctor of Science',
	'Doctor of Veterinary Medicine',
	'Juris Doctor',
	'High School Diploma',
	'GED',
	'Certificate',
	'Undergraduate Certificate',
	'Graduate Certificate',
	'Postgraduate Diploma',
	'Diploma',
];
