// The major, concentration, and minor have their own fields, so only general degree names belong here.
export const DEGREES: readonly string[] = [
	'Associate of Arts',
	'Associate of Science',
	'Associate of Applied Science',
	'Bachelor of Arts',
	'Bachelor of Science',
	'Bachelor of Applied Science',
	'Bachelor of Business Administration',
	'Bachelor of Engineering',
	'Bachelor of Fine Arts',
	'Master of Arts',
	'Master of Science',
	'Master of Business Administration',
	'Master of Education',
	'Master of Engineering',
	'Master of Fine Arts',
	'Doctor of Philosophy',
	'Doctor of Education',
	'Doctor of Medicine',
	'Juris Doctor',
	'High School Diploma',
	'GED',
	'Certificate',
	'Diploma',
];
