export const MAJORS: readonly string[] = [
	'Accounting',
	'Actuarial Science',
	'Adult Education',
	'Advertising',
	'Aerospace Engineering',
	'African American Studies',
	'Agribusiness',
	'Agricultural Engineering',
	'Agriculture',
	'American Studies',
	'Ancient History',
	'Animal Science',
	'Animation',
	'Anthropology',
	'Applied Linguistics',
	'Applied Mathematics',
	'Applied Physics',
	'Applied Psychology',
	'Archaeology',
	'Architectural Engineering',
	'Architecture',
	'Art',
	'Art Education',
	'Art History',
	'Astronomy',
	'Astrophysics',
	'Athletic Training',
	'Atmospheric Science',
	'Audio Production',
	'Biochemistry',
	'Bioengineering',
	'Bioinformatics',
	'Biology',
	'Biomedical Engineering',
	'Biomedical Science',
	'Biostatistics',
	'Botany',
	'Business Administration',
	'Business Analytics',
	'Chemical Engineering',
	'Chemistry',
	'Cinema Studies',
	'Civil Engineering',
	'Classics',
	'Clinical Psychology',
	'Cognitive Science',
	'Commerce',
	'Communication Sciences and Disorders',
	'Comparative Literature',
	'Computational Biology',
	'Computer Engineering',
	'Computer Science',
	'Construction Management',
	'Corporate Finance',
	'Creative Writing',
	'Criminal Justice',
	'Criminology',
	'Cultural Studies',
	'Curriculum and Instruction',
	'Cybersecurity',
	'Dance',
	'Data Analytics',
	'Data Science',
	'Dental Hygiene',
	'Dentistry',
	'Developmental Psychology',
	'Dietetics',
	'Digital Arts',
	'Dispute Resolution',
	'Dramatic Arts',
	'Early Childhood Education',
	'Earth Science',
	'East Asian Studies',
	'Ecology',
	'Economics',
	'Education',
	'Educational Administration',
	'Educational Leadership',
	'Educational Technology',
	'Electrical Engineering',
	'Elementary Education',
	'English Language and Literature',
	'English Literature',
	'Entrepreneurship',
	'Environmental Engineering',
	'Environmental Science',
	'Ethics',
	'European Studies',
	'Exercise Science',
	'Fashion Design',
	'Film and Media Studies',
	'Film Production',
	'Finance',
	'Financial Engineering',
	'Fine Arts',
	'Food Science',
	'Forensic Science',
	'Forestry',
	'French Language and Literature',
	'Game Design',
	'Gender Studies',
	'Genetics',
	'Geography',
	'Geology',
	'Geophysics',
	'German Language and Literature',
	'Global Studies',
	'Graphic Design',
	'Health Administration',
	'Health Informatics',
	'Health Sciences',
	'Higher Education',
	'History',
	'Homeland Security',
	'Hospitality Management',
	'Human Development',
	'Human Resource Management',
	'Humanities',
	'Illustration',
	'Industrial Design',
	'Industrial Engineering',
	'Information Systems',
	'Information Technology',
	'Insurance and Risk Management',
	'Interior Design',
	'International Business',
	'International Law',
	'International Relations',
	'Kinesiology',
	'Latin American Studies',
	'Law',
	'Legal Studies',
	'Linguistics',
	'Logistics and Supply Chain Management',
	'Management',
	'Management Information Systems',
	'Marine Biology',
	'Marketing',
	'Materials Science and Engineering',
	'Mathematics',
	'Mathematics Education',
	'Mechanical Engineering',
	'Mechatronics Engineering',
	'Medical Laboratory Science',
	'Medicine',
	'Microbiology',
	'Middle Eastern Studies',
	'Molecular Biology',
	'Music',
	'Music Education',
	'Music Performance',
	'Music Production',
	'Neuroscience',
	'Nuclear Engineering',
	'Nursing',
	'Nutrition and Dietetics',
	'Occupational Therapy',
	'Oceanography',
	'Operations Management',
	'Operations Research',
	'Optometry',
	'Paralegal Studies',
	'Peace and Conflict Studies',
	'Petroleum Engineering',
	'Pharmacy',
	'Philosophy',
	'Photography',
	'Physical Education',
	'Physical Therapy',
	'Physician Assistant Studies',
	'Physics',
	'Political Science',
	'Psychology',
	'Public Administration',
	'Public Health',
	'Public Policy',
	'Radiologic Technology',
	'Real Estate',
	'Religious Studies',
	'Rhetoric and Composition',
	'Robotics Engineering',
	'Science Education',
	'Secondary Education',
	'Social Work',
	'Sociology',
	'Software Engineering',
	'Spanish Language and Literature',
	'Special Education',
	'Speech-Language Pathology',
	'Statistics',
	'Structural Engineering',
	'Studio Art',
	'Supply Chain Management',
	'Systems Engineering',
	'Theatre',
	'Theology',
	'Urban Planning',
	'Urban Studies',
	'Veterinary Medicine',
	'Visual Arts',
	'Zoology',
];
